PickNikRobotics/rviz_visual_tools

include/rviz_visual_tools/rviz_visual_tools.h
src/rviz_visual_tools.cpp

Added a clear overlay... for the times you don't want to be blue.

added a clear overlay

---

include/rviz_visual_tools/rviz_visual_tools.h
src/rviz_visual_tools.cpp

added method for displaying cuboids

---

src/rviz_visual_tools.cpp

woops.
forgot to rename everything...

Sorry, forgot to change variable names

---

include/rviz_visual_tools/rviz_visual_tools.h
src/rviz_visual_tools.cpp

Found this to be helpful when I didn't already have poses / geom messages.

new publishLine function takes two Vector3's

---

include/rviz_visual_tools/rviz_visual_tools.h
src/rviz_visual_tools.cpp

Removed random pose bounds member variable in favor of using a function parameter

---

include/rviz_visual_tools/rviz_visual_tools.h
src/rviz_visual_tools.cpp

Enhance wireframe cuboids: now you only need to specify depth/width/height and pose.
Tested/working.

Wireframe hdw

---

include/rviz_visual_tools/rviz_visual_tools.h
src/rviz_visual_tools.cpp

Something is wrong in the test though... the colors change when new planes are published.
I'm guessing it's something wrong with the ID or header, but I can't figure it out.

added publish plane and cone

---

README.md
include/rviz_visual_tools/rviz_visual_tools.h
src/rviz_visual_tools.cpp

I'd like to sync my jade branch, which I've been developing the past couple years, into the indigo branch so I can release it into indgo as a debian.
* Is anyone actively using my debians and are you ok if I sync this? *
there are breaking changes.
@mcevoyandy

BREAKING API CHANGE

---

include/rviz_visual_tools/rviz_visual_tools.h
src/rviz_visual_tools.cpp

@davetcoleman, @VictorLamoine , we added some modifications in the waitForSubscriber function. The parameters 'bool blocking' if true allow to loop inside the function until we get a subscriber attached.

Added blocking constraint option in function waitForSubscriber

---

include/rviz_visual_tools/rviz_visual_tools.h
src/rviz_visual_tools.cpp

http://eigen.tuxfamily.org/dox/group__TopicPassingByValue.html

Do not pass Eigen structures by value

---

.travis.yml

Improve Travis script

---

.travis.yml

Per https://github.com/ros-infrastructure/ros_buildfarm/blob/master/doc/jobs/devel_jobs.rst

Testing new ROS Buildfarm Travis Script

---

CMakeLists.txt
package.xml

Same as https://github.com/davetcoleman/rviz_visual_tools/pull/44 into `kinetic-devel`

Catkin depend on eigen and tf conversions

---

tests/rvt_test.cpp

Fix deprecated calls to convertFromXYZRPY

---

src/tf_visual_tools.cpp

Moves https://github.com/davetcoleman/rviz_visual_tools/pull/55 to kinetic
@mlautman

Normalize quaternion before storage

---

include/rviz_visual_tools/imarker_simple.h
include/rviz_visual_tools/rviz_visual_tools.h
src/imarker_simple.cpp
src/imarker_simple_demo.cpp
src/key_tool.h
src/rviz_visual_tools.cpp

Includes https://github.com/PickNikRobotics/rviz_visual_tools/pull/67 - merge that one first

Code quality

---

CMakeLists.txt

So nothing else should be wrapped by hand.
I overlooked this when I first looked into this.
This hopefully addresses https://github.com/PickNikRobotics/rviz_visual_tools/pull/74#issuecomment-380391

Trust AUTOMOC

---

CMakeLists.txt

Per comment: https://github.com/isys-vision/rviz_visual_tools/commit/65835849130b49562db53ea5da63a2ae51c6180f#commitcomment-29579582
@simonschmeisser please review

Automoc requires at least cmake version 2.8.6

---

CMakeLists.txt

Closes https://github.com/PickNikRobotics/rviz_visual_tools/issues/87
@ahoarau seems we need to do other things to enable ccache, like tweak the catkin command or... ?

Add ccache support

---

MIGRATION.md
README.md
include/rviz_visual_tools/imarker_simple.h
include/rviz_visual_tools/rviz_visual_tools.h
include/rviz_visual_tools/tf_visual_tools.h
src/imarker_simple.cpp
src/rviz_visual_tools.cpp
src/rviz_visual_tools_demo.cpp
src/tf_visual_tools.cpp
tests/rvt_test.cpp

See https://github.com/ros-planning/moveit/pull/1096
Must be merged at the same time as moveit's
@rhaschke

Fix Eigen::Affine3d for Melodic (using Eigen::Isometry3d)

---

src/rviz_visual_tools.cpp

See http://moveit.ros.org/documentation/contributing/code/

Use LOGNAME for logging re:moveit style

---

.github/auto_assign.yml

Only auto-assign one reviewer

---

src/rviz_visual_tools_demo.cpp

Fixes #96, to test, you also need https://github.com/PickNikRobotics/rviz_visual_tools/pull/110

Initizalize quaternions in demo to avoid warning

---

include/rviz_visual_tools/rviz_visual_tools.h
src/rviz_visual_tools.cpp
tests/rvt_test.cpp

Fixes #73 
Isn't there a better way to handle this problem in C++ ?! Like making one of the function preferred?

Remove default arguments to make function calls not ambiguous

---

include/rviz_visual_tools/rviz_visual_tools.h
package.xml
src/rviz_visual_tools.cpp
src/rviz_visual_tools_demo.cpp

For ABCD planes: better comments, ensure the plane equation is satisfied.

---

.clang-tidy
.travis.yml
include/rviz_visual_tools/deprecation.h
include/rviz_visual_tools/imarker_simple.h
include/rviz_visual_tools/remote_control.h
include/rviz_visual_tools/remote_reciever.h
include/rviz_visual_tools/rviz_visual_tools.h
include/rviz_visual_tools/tf_visual_tools.h
src/key_tool.h
src/rviz_visual_tools.cpp
src/rviz_visual_tools_demo.cpp
src/rviz_visual_tools_gui.h
src/tf_visual_tools.cpp
tests/rvt_test.cpp

As a side note: I used run-clang-tidy-7.py from clang-tidy-7 and clang-tools-7 -- I don't think that it could make any difference.

Apply clang-tidy

---

.github/auto_assign.yml
.travis.yml
README.md

@JafarAbdi be sure to configure your editor to trim trailing whitespace on save.

remove trailing whitespaces

---

CMakeLists.txt
include/rviz_visual_tools/imarker_simple.hpp
src/imarker_simple.cpp
src/imarker_simple_demo.cpp
src/rviz_visual_tools.cpp

Some minor cleanup to the Imarker Simple lib,
Also some meaningful changes to the CMakeLists.txt

Eloquent cleanup

---

include/rviz_visual_tools/imarker_simple.hpp
include/rviz_visual_tools/rviz_visual_tools.hpp
launch/demo_combined.launch.py
launch/demo_rviz.launch.py
src/imarker_simple.cpp
src/rviz_visual_tools.cpp
src/rviz_visual_tools_demo.cpp

fixing the wait for subscriber time to use seconds rather than nanoseconds

fix waitForSubscriber time

---

CMakeLists.txt
include/rviz_visual_tools/rviz_visual_tools.hpp
src/imarker_simple.cpp
src/imarker_simple_demo.cpp
src/rviz_visual_tools.cpp
src/rviz_visual_tools_demo.cpp
tests/rvt_test.cpp

Fix .dll loading and M_PI extension

Compilation for Windows

---

CMakeLists.txt
package.xml
src/rviz_visual_tools.cpp
src/tf_visual_tools.cpp
tests/rvt_test.cpp

tf is deprecated, replaced it with tf2_eigen for noetic

replace tf_conversions with tf2

---

.travis.yml

The current Travis config file is broken for melodic-devel branch

Update .travis.yml for melodic-devel

---

include/rviz_visual_tools/imarker_simple.h
src/imarker_simple.cpp
src/key_tool.h
src/rviz_visual_tools_gui.h

Allow the imarker parent frame to be something other than world

Add optional parent frame to iMarker

---

CMakeLists.txt
package.xml

This is a follow up for https://github.com/ros-planning/moveit_visual_tools/pull/75.

[noetic] Adding missing dependency (interactive_markers)

---

CHANGELOG.rst
CMakeLists.txt
package.xml

These changes were only made on noetic-devel and also belong here on master.

Forwardport changes from noetic-devel

---

.travis.yml
include/rviz_visual_tools/imarker_simple.hpp
include/rviz_visual_tools/key_tool.hpp
include/rviz_visual_tools/remote_control.hpp
include/rviz_visual_tools/remote_reciever.hpp
include/rviz_visual_tools/rviz_visual_tools.hpp
include/rviz_visual_tools/rviz_visual_tools_gui.hpp
src/imarker_simple.cpp
src/remote_control.cpp
src/rviz_visual_tools.cpp
src/rviz_visual_tools_demo.cpp
src/rviz_visual_tools_gui.cpp
src/tf_visual_tools.cpp
tests/rvt_test.cpp

Updated to offer shared_ptr to create_timer for foxy support due to the change of API specification from eloquent.
Background and details are described in https://github.com/PickNikRobotics/rviz_visual_tools/issues/178.
Thank you in advance!

Foxy support

---

src/remote_control.cpp

`rclcpp::executor::FutureReturnCode` was removed

Fix build with rolling

---

.github/workflows/format.yaml
.github/workflows/industrial_ci_action.yaml
README.md
src/rviz_visual_tools.cpp
src/tf_visual_tools.cpp

Since we are also running Galactic and Rolling, I thought it would make sense to start a `ros2` branch from `foxy-devel`. This PR also includes the header guards required to silence deprecation warnings in Rolling.
This PR addresses #192

Fixes for new ros2 branch

---

CHANGELOG.rst
package.xml

`git tag` must be pushed manually once this PR gets merged.

ros2: Update version number to 4.1.0

---

package.xml

Need a F/R/G release after this.

Backport - Make sure to add all dependencies to the package.xml (#209)

---

include/rviz_visual_tools/rviz_visual_tools.hpp
src/rviz_visual_tools.cpp

Add a convenience method to publish a plane using a normal and an offset

Add a method to publish a plane using the normal and distance

---

src/rviz_visual_tools.cpp

Minor typo fix

---

include/rviz_visual_tools/imarker_simple.hpp
src/imarker_simple.cpp

This PR is essentially the same as https://github.com/PickNikRobotics/rviz_visual_tools/pull/159 except targeting the ros2 branch
@nbbrooks , @AndyZe , @tylerjw

[ros2] pass in parent frame for imarker

---

.github/workflows/format.yaml
.github/workflows/industrial_ci_action.yaml

Silence deprecation warnings
Replaces #255
Replaces #253

CI: Update actions
