PickNikRobotics/rviz_visual_tools

include/rviz_visual_tools/rviz_visual_tools.h, src/rviz_visual_tools.cpp
In our application, we have separate nodes to launch rviz and markers_viewer using this package. The two packages start at different times. When rviz is launched after the markers are done publishing, markers are missed by the rviz to be displayed.
Making the publisher latched will solve this problem of not having the subscriber(rviz) at the time of publishing.
=> Latched publisher

include/rviz_visual_tools/rviz_visual_tools.h
https://eigen.tuxfamily.org/dox-devel/group__TopicStructHavingEigenMembers.html
Otherwise there could be issues on 32 bits architectures.
=> Overload new operator for Eigen structures

CMakeLists.txt, package.xml
We need `eigen_conversions` and `tf_conversions` in `CATKIN_DEPENDS`, so the executables (or libraries) linking against this library build without adding those dependencies on them, since it's actually a (transitive) dependency of `rviz_visual_tools`.
Error:
``` bash
/usr/bin/ld: warning: libeigen_conversions.so, needed by /opt/ros/indigo/lib/librviz_visual_tools.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libtf_conversions.so, needed by /opt/ros/indigo/lib/librviz_visual_tools.so, not found (try using -rpath or -rpath-link)
/opt/ros/indigo/lib/librviz_visual_tools.so: undefined reference to `tf::pointEigenToMsg(Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, geometry_msgs::Point_<std::allocator<void> >&)'
/opt/ros/indigo/lib/librviz_visual_tools.so: undefined …
```
=> Catkin depend on eigen and tf conversions

src/rviz_visual_tools.cpp
This makes irregularly scaled spheres (i.e. ellipsoids) to be rendered correctly, which isn't the case when using `SPHERE_LIST` type markers.
See ros-visualization/rviz#1038.
=> Change the sphere marker type from SPHERE_LIST to SPHERE.

include/rviz_visual_tools/rviz_visual_tools.h, src/rviz_visual_tools.cpp
It's me again :)
I have changed the function documentation, I think it was hard to make the difference between `publishLines` and `publishPath`, this description should be more explicit.
I added a new variant of `publishPath` that allows publishing cylinders (as a path) with custom colors.
It was possible with `publishLines` and I think it's useful with `publishPath` too!
=> Allow publishPath with std_msgs::ColorRGBA

include/rviz_visual_tools/rviz_visual_tools.h, src/rviz_visual_tools.cpp
`publishArrow()` is now overloaded to create an arrow between two points.
=> added arrow pub to take two points

CMakeLists.txt
This wouldn't link otherwise, on OSX.
=> add linking to visualization tools library for imarker_simple

include/rviz_visual_tools/rviz_visual_tools.h
Ambiguous function call for. Removed `length` default value so the `geometry_msgs` call matched the `eigen` call.
=> fix for ambiguous function call to publishAxis

src/tf_visual_tools.cpp
Prevents `TF_DENORMALIZED_QUATERNION`  errors in TF2 from happening. Version 0.5.15 release of tf2 checks for quaternion normalization.
=> Normalize quaternion before storage

src/rviz_visual_tools.cpp
Closely related to https://github.com/ros-visualization/rviz/pull/1179
Not sure if there are other places where invalid quaternions still stand.
Cannot hurt!
=> Reset marker should publish initialized quaternion

CMakeLists.txt
I have no idea why this ever worked, but it broke on my system (non-ubuntu) just now.
Apparently you forgot to link the autogenerated qt code into the library that provides the classes.
Fixes \#71.
=> link qt code into the _gui library

CMakeLists.txt
```
$ catkin_lint -W3 .
rviz_visual_tools: notice: target name 'imarker_simple_demo' might not be sufficiently unique
rviz_visual_tools: CMakeLists.txt(15): notice: list COMPONENTS should be sorted
rviz_visual_tools: CMakeLists.txt(35): notice: operands for operator VERSION_LESS should be quoted strings
rviz_visual_tools: CMakeLists.txt(54): notice: list CATKIN_DEPENDS should be sorted
rviz_visual_tools: CMakeLists.txt(86): notice: list of source files should be sorted
rviz_visual_tools: CMakeLists.txt(149): notice: list TARGETS should be sorted
rviz_visual_tools: CMakeLists.txt(173): notice: list TARGETS should be sorted
catkin_lint: checked 1 packages and found 7 problems
```
```
$ catkin_lint -W3 .
rviz_visual_tools: notice: target name 'imarker_simple_demo' might not be sufficiently …
```
=> Improve package with catkin_lint

MIGRATION.md, src/rviz_visual_tools.cpp
calling ros::spinOnce() in random places ( ;) ) messes up threading. This causes updates to PlanningSceneMonitor and joint state to be handled in our gui thread as opposed to the async spinner thread where we intended them to be handled.
=> no ros::spinOnce()

README.md
Mostly I'm trying to test probot...
=> Update README Kinetic to Melodic

CMakeLists.txt
This silents some `catkin_lint` warnings
```bash
$ catkin_lint -W3 .
rviz_visual_tools: notice: target name 'imarker_simple_demo' might not be sufficiently unique
rviz_visual_tools: CMakeLists.txt(90): notice: list of source files should be sorted
rviz_visual_tools: CMakeLists.txt(177): notice: list TARGETS should be sorted
catkin_lint: checked 1 packages and found 3 problems
```
```bash
catkin_lint -W3 .
rviz_visual_tools: CMakeLists.txt(90): notice: list of source files should be sorted
catkin_lint: checked 1 packages and found 1 problems
```
You can't do much about the last warning because `catkin_lint` expect sorted lists of files even with when variables are used.
=> Fix some catkin_lint warnings

launch/demo.launch, launch/demo_combined.launch
I forgot to change the names of the nodes in the launch files after renaming them (https://github.com/PickNikRobotics/rviz_visual_tools/pull/98).
This fixes the launch files for the demo.
=> Fix node type in demo launch files

CMakeLists.txt, include/rviz_visual_tools/rviz_visual_tools.h, include/rviz_visual_tools/tf_visual_tools.h, package.xml, src/rviz_visual_tools.cpp, src/tf_visual_tools.cpp
In this PR, I would like to propose two changes:
* I try to publish the camera FOV marker shown below, but I only found the function to publish from the mesh source file, instead of publishing from the triangle mesh created online. Therefore, I propose to add a feature for this.
* In the second change, I would like to make it possible that the transforms published by `tf_visual_tools` can be reset. This can allow me to publish a new transform with a different `from_frame` to replace a previously published transform, otherwise they will coexist.
=> Make `rviz_visual_tools` publish triangle mesh and `tf_visual_tools` clean published transforms

CMakeLists.txt, include/rviz_visual_tools/rviz_visual_tools.h
Enable Windows build for `rviz_visual_tools`:
* Follow `catkin` guidance to install binaries to the correct locations.
http://docs.ros.org/kinetic/api/catkin/html/howto/format1/building_libraries.html
http://docs.ros.org/kinetic/api/catkin/html/howto/format1/building_executables.html
* Use the `win_ros` conventions to handle DLL export issues: 
http://wiki.ros.org/win_ros/Contributing/Dll%20Exports
`WINDOWS_EXPORT_ALL_SYMBOLS` is enabled from `catkin` but there are limitation for that approach, so this DLL export change is still required in some cases. For details, please see [here](https://blog.kitware.com/create-dlls-on-windows-without-declspec-using-new-cmake-export-all-feature/).
* Conditionally include the GCC specific warning and compiler flags to unblock MSVC build.
=> [Windows][melodic] Enable Windows build

.clang-format, .gitignore, .travis.yml, include/rviz_visual_tools/rviz_visual_tools.h, src/rviz_visual_tools.cpp, src/rviz_visual_tools_demo.cpp, tests/rvt_test.cpp
This repo was using a bad CI approach and not using our best practices
=> Switch to moveit_ci, apply clang-format

.github/auto_assign.yml
@mamoll fyi we use a bot to auto-assign PRs for some of our repos, though the OA can always manually assign people also (like I did here)
fyi @JafarAbdi this answers your question about who to assign it to
=> Remove auto-bot for assignees, update reviewers

src/rviz_visual_tools.cpp
Rviz has become increasingly strict about normalizing your quaternions. 
This simply normalizes them for you unless they are initialized in which case they are set to [1, 0, 0, 0]
=> normalize before publish

src/imarker_simple.cpp
Quaternions for rotation should have a magnitude of 1
=> Normalize interactive marker quaternions.

include/rviz_visual_tools/rviz_visual_tools.h, src/rviz_visual_tools.cpp
The warnings were getting very spammy. 
eg:
```
ros.rviz: Marker 'Wireframe Cuboid/1124': scale.y and scale.z of LINE_LIST or LINE_STRIP are ignored.
ros.rviz: Marker 'Wireframe Cuboid/1125': scale.y and scale.z of LINE_LIST or LINE_STRIP are ignored.
ros.rviz: Marker 'Wireframe Cuboid/1126': scale.y and scale.z of LINE_LIST or LINE_STRIP are ignored.
ros.rviz: Marker 'Wireframe Cuboid/1127': scale.y and scale.z of LINE_LIST or LINE_STRIP are ignored.
ros.rviz: Marker 'Wireframe Cuboid/1128': scale.y and scale.z of LINE_LIST or LINE_STRIP are ignored.
ros.rviz: Marker 'Wireframe Cuboid/1129': scale.y and scale.z of LINE_LIST or LINE_STRIP are ignored.
ros.rviz: Marker 'Wireframe Cuboid/1130': scale.y and scale.z of LINE_LIST or LINE_STRIP are ignored.
ros.rviz: Marker 'Wireframe …
```
=> fix rviz warnings about scale and uninitialized quaternions

CMakeLists.txt, include/rviz_visual_tools/key_tool.hpp, include/rviz_visual_tools/remote_reciever.hpp, include/rviz_visual_tools/rviz_visual_tools_gui.hpp, package.xml, plugin_description.xml, src/key_tool.cpp, src/rviz_visual_tools_gui.cpp
rviz_visual_tools_gui changes / port from old ros1 rviz class names etc.
-     changed remote_reciever to inherit from rclcpp::Node hence be its own node to publish joystick messages
-     changed rviz_visual_tools_gui to use rviz2 classes (e.g. rviz_common instead of rviz)
-     some changes to CMakeLists to compile properly and rviz2 to load the plugin
plugins load fine for me with ubuntu 18.04 / eloquent and publish joystick messages properly. 
KeyTool only works for A key with me since other keys seem to jump to other tools.
=> Fix rviz_visual_tools_gui

include/rviz_visual_tools/rviz_visual_tools.h, src/rviz_visual_tools.cpp
=> Backport get_identity_pose

src/key_tool.h, src/rviz_visual_tools_gui.h
Clang-tidy is failing on master branch [see](https://travis-ci.org/github/PickNikRobotics/rviz_visual_tools/jobs/694010598)
=> Fix clang-tidy for master branch

CHANGELOG.rst, CMakeLists.txt
This adds the soname versions to the libraries in anticipation of a Noetic release so if we do want to release Noetic a second time in the future with breaking changes the version of the library increases and it is discovered while linking if someone has linked incompatible versions.
=> [maint] add soname versions to libraries

include/rviz_visual_tools/rviz_visual_tools.h, src/imarker_simple_demo.cpp, src/rviz_visual_tools.cpp
rand/srand were probably already deprecated by the time this code was written...
I took the error on MoveIt's CI as an incentive to migrate to std::random:
As example code referred to a seeding step, I added an explicit setRandomSeed to the API.
This is required to fix MoveIt's CI: https://github.com/ros-planning/moveit/pull/2792/commits/2989f44e50ea10a1bc1ef833d39bac766daf61f5
<<<
rviz_visual_tools.cpp:2810:42: error: implicit conversion from 'int' to 'float' changes value from 2147483647 to 2147483648 [-Werror,-Wimplicit-int-float-conversion]
float d = static_cast<float>(rand()) / RAND_MAX;
~ ^~~~~~~~
/usr/include/stdlib.h:86:18: note: expanded from macro 'RAND_MAX'
^~~~~~~~~~
<<<
Please review @nbbrooks @tylerjw @JafarAbdi
=> migrate to <random>

.github/workflows/industrial_ci_action.yaml
Our ccache is broken in CI, thus our ccache action should be updated to match Github's new ccache action v2 as per https://github.com/ros-planning/moveit2/pull/619
=> [foxy] Fix ccache

package.xml
This package is failing to build on Rolling due to the missing pluginlib dependency declaration.
The existing dependencies do not appear to be lexically ordered so I sort of plopped pluginlib in somewhere that "seemed reasonable". I'm happy to rework this PR to fit what you need, or maintainer edits are on so you can tweak it to your preference.
This is primarily intended as notification that Rolling builds for this package are currently failing and a proposed solution for the current issue.
=> Add pluginlib dependency.

package.xml
Otherwise it will fail to build on the buildfarm.
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>
This should fix the failing build, e.g. https://build.ros2.org/view/Rbin_uF64/job/Rbin_uF64__rviz_visual_tools__ubuntu_focal_amd64__binary/54/console
=> Make sure to add all dependencies to the package.xml

include/rviz_visual_tools/tf_visual_tools.hpp, src/tf_visual_tools.cpp
There was a faulty templated constructor in tf_visual_tools header causing various weird issues in moveit_calibration. This should fix it. Thanks @JafarAbdi for helping me with this.
Alternative solution at #212.
=> Fix faulty templated constructor

include/rviz_visual_tools/rviz_visual_tools.hpp, src/rviz_visual_tools.cpp
This adds the option of remembering that the user does not want to wait for a publisher before sending the MarkerArray.
After setting up the object if the user calls visual_tools_->loadMarkerPub(false); the object will no longer wait for listeners on the marker topic.
=> Add option to never wait for subscriber

include/rviz_visual_tools/remote_control.h, src/remote_control.cpp
The `RemoteControl` class currently [spins the global queue when waiting for the user to confirm](https://github.com/PickNikRobotics/rviz_visual_tools/blob/9b10fd2d96f9f2aa8177052e4dc35df8ce914003/src/remote_control.cpp#L16jk0).
It does so because the node handle for the subscriber that receives the feedback is usually initialized with the global callback queue. But that also means that other callbacks (including the one currently running!) can be processed in the thread that is waiting for user input and it's easy to block all available spinners or get into recursive spin calls for the same topic.
Even worse, there is no workaround: Even if the user provides a node handle with a different callback queue, the calls to `spinOnce` will not even process that queue but the method calls still …
=> spin independent thread for RemoteControl

include/rviz_visual_tools/rviz_visual_tools.h, src/rviz_visual_tools.cpp
waitForSubscriber used to call ros::spinOnce() which could trigger
callbacks from other topics in other threads. In case those have a lock
to only get called once, this would look the visual_tools thread.
Closes: #146
=> Move pub_rviz_markers_ to it's own callback queue

.github/workflows/format.yaml, .pre-commit-config.yaml
This should fix formatting failures in CI because the pre-commit version was lagging what's actually done in the GitHub actions workflow.
=> Upgrade to clang-format-14

README.md, include/rviz_visual_tools/rviz_visual_tools.hpp, src/rviz_visual_tools.cpp
This PR expands the interfaces for `publishCuboid()` so we can pass in any general `std_msgs::msg::ColorRGBA` color rather than just the predefined enums.
I also snuck in a one-line link fix to the README
=> Add arbitrary color option to `publishCuboid`

src/key_tool.cpp
When building, I get the following message:
```
In file included from /workspaces/ros2-rolling-ws/src/rviz_visual_tools/src/key_tool.cpp:30:
/opt/ros/rolling/opt/rviz_ogre_vendor/include/OGRE/OgreVector3.h:2:62: note: ‘#pragma message: /opt/ros/rolling/opt/rviz_ogre_vendor/include/OGRE/OgreVector3.h is deprecated, migrate to Ogre.h’
2 | #pragma message( __FILE__ " is deprecated, migrate to Ogre.h")
```
This PR uses Ogre.h instead of the deprecated OgreVector3.h as per the message suggests.
=> Migrate to Ogre.h

src/rviz_visual_tools.cpp
`publishNormalAndDistancePlane` function takes as parameters color nad size of the published plane. Unfortunately those parameters were unused, this PR fixes this issue.
=> Fix unused variables in publishNormalAndDistancePlane

CMakeLists.txt, package.xml
This is required to compile with debian's `pluginlib-dev` package which isolates the headers.
The include is required [here](https://github.com/PickNikRobotics/rviz_visual_tools/blob/8703caf0d994e346487748afdafd7c85b845031c/src/rviz_visual_tools_gui.cpp#L124-L125) and [here](https://github.com/PickNikRobotics/rviz_visual_tools/blob/8703caf0d994e346487748afdafd7c85b845031c/src/key_tool.cpp#L101-L102).
=> [ROS-O] add missing pluginlib dependency
